config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get 'signup' => 'users#new'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :users
  resources :posts, only: [:create, :destroy]

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 250 }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts, dependent: :destroy
 # used to set the default order in which elements are retrieved from the database
 default_scope -> { order(created_at: :desc) }
 # callback ensures email uniqueness by downcasing the email attribute
 before_save { self.email = email.downcase }
 validates :name, presence: true, length: { maximum: 25 }
 validates :email, presence: true, length: { maximum: 50 }, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }, uniqueness: { case_sensitive: false }

 has_secure_password
 validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper

  private

  # Confirms a logged-in user.
  def logged_in_user
    unless logged_in?
      flash[:danger] = "Please log in."
      redirect_to login_path
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]
  before_action :correct_user, only: :destroy

  def index
    @posts = Post.all
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = "Post was created."
      redirect_to user_path(current_user)
    else
      flash.now[:danger] = "Post has not been created."
      render "static_pages/home"
      # render 'users/show'
      # render {:action => "show", :controller => "users"}
      # render :controller => :users, :action => :show
      # render "/controller/action"
      # render :template => "users/show"
    end
  end

  def destroy
    @post.destroy
    flash[:success] = "Post was deleted."
    redirect_to request.referrer || root_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :content)
  end

  def correct_user
      @post = current_user.posts.find_by(id: params[:id])
      redirect_to root_url if @post.nil?
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    # finds the user in the db using the submitted email address
    user = User.find_by(email: params[:session][:email].downcase)
    # determine if the resulting user's email and password are valid (exist in the db)
    if user && user.authenticate(params[:session][:password])
      # Log the user in and redirect to the user's show page.
      log_in user
      redirect_to user
    else
      flash.now[:danger] = "Invalid email/password combination."
      render "new"
    end
  end

  def destroy
    log_out
    redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user, only: :destroy

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user # the user is logged in upon signup
      flash[:success] = "Welcome, your account has been created."
      redirect_to @user
    else
      flash.now[:danger] = "Your account has not been created."
      render "new"
    end
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts
    @post = current_user.posts.build if logged_in?
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
  @user = User.find(params[:id])
  if @user.update(user_params)
    flash[:success] = "Profile has been updated."
    redirect_to @user
  else
    render "edit"
  end
end

def destroy
  User.find(params[:id]).destroy
  flash[:success] = "User deleted."
  redirect_to users_path
end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  # Before filters

  # Confirms the correct user.
  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_path) unless @user == current_user
  end

  # confims an admin user, setting access control to the destroy action
  def admin_user
    redirect_to(root_path) unless current_user.admin?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title = "")
    base_title = "Blogger App"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # Logs in the given user.
  def log_in(user)
    # rails method: make temporary cookies using the session method that are automatically encrypted and expire automatically on browser close
    session[:user_id] = user.id
  end

  # Returns the current logged-in user (if any).
  def current_user
    # storing in a instance variable, which hits the db the 1st time but
    # returns the instance variable immediately on subsequents invocations
    @current_user ||= User.find_by(id: session[:user_id])
  end

  # Returns true if the given user is the current user, also replaces the current_user method
  def current_user?(user)
    user == current_user
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  # Logs out the current user.
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="http://www.google.com/">Blogger App</a>
    by <a href="http://www.google.com/">H. Sandoval</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Blogger App", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help",'#' %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", users_path %></li>
          <li><%= link_to "Profile", current_user %></li>
          <li><%= link_to "Settings", edit_user_path(current_user) %></li>
          <li><%= link_to "Log out", logout_path, method: "delete" %></li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render "layouts/shim" %>
</head>
<body>
  <div class="container">
    <%= render "layouts/header" %>
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>

    <%= yield %>

    <%= render "layouts/footer" %>
  </div>
</body>
</html>

app/views/posts/_post.html.erb
<li>
  <span class="content"><%= link_to post.user.name, post.user %></span>
  <span class="content"><%= post.title %></span>
  <span class="content"><%= post.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(post.created_at) %> ago.
    <% if current_user?(post.user) %>
      <%= link_to "delete", post, method: :delete, data: { confirm: "You sure?" } %>
    <% end %>
  </span>
</li>

app/views/posts/index.html.erb
<% provide(:title, 'All posts') %>
<h1>All posts</h1>

<ul class="users">
  <% @posts.each do |post| %>

  <% link_to post.user.name, post.user %>
  <%= post.title %>
  <%= post.content %>

    Posted <%= time_ago_in_words(post.created_at) %> ago.

  <% end %>
</ul>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_post_form.html.erb
<%= form_for(@post) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_field :title, placeholder: "New title here..." %>
    <%= f.text_area :content, placeholder: "Compose new post..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

app/views/shared/_user_info.html.erb
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.posts.count, "post") %></span>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<div class="jumbotron">
  <h1>Welcome to the Blogger App</h1>
  <h2>
    Welcome! This is the home page for the
    <a href="http://www.google.com/">Blogger</a> Application.
  </h2>

  <%= link_to "Sign up!", signup_path, class: "btn btn-lg btn-primary" %>
</div>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %><br>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %><br>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %><br>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %><br>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= link_to user.name, user %>
      <% if current_user.admin? && !current_user?(user) %> | <%= link_to "delete", user, method: :delete, data: { confirm: "You sure?" } %>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">

    <section class="user_info">
      <%= render 'shared/user_info' %>
    </section>
    <section class="post_form">
      <%= render 'shared/post_form' %>
    </section>

  </aside>

  <div class="col-md-8">
    <% if @user.posts.any? %>
      <h3>Posts (<%= @user.posts.count %>)</h3>
      <ol class="posts">

        <%= render @posts %>

      </ol>
    <% end %>
  </div>
</div>